name: Test

on: [push,pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2022.04.08'

      - uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.10.1.469'

      - uses: actions/checkout@v1

      - name: Cache dependencies lint
        run: echo "$(clj-kondo --lint \"$(clojure -Spath -A:provided)\") --parallel"

      - name: Run linter
        run: clj-kondo --lint src test

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.10.1.469'

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.2.1
        with:
          babashka-version: 0.3.6

      - uses: actions/checkout@v1

      - run: bb run format-check

  test-clj:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.10.1.469'

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.2.1
        with:
          babashka-version: 0.3.6

      - name: Cache maven
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('deps.edn') }}
          restore-keys: |
            m2-

      - run: bb run test
